// Generated by Supabase MCP from the live schema.
// Regenerate with: mcp__adc052c3-...__generate_typescript_types({ project_id })
// or via Supabase CLI: `npx supabase gen types typescript`
//
// Don't hand-edit — re-run the generator after any migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_users: {
        Row: {
          active: boolean
          auth_user_id: string
          created_at: string
          email: string
          full_name: string
          id: string
          role: Database["public"]["Enums"]["admin_role"]
          updated_at: string
        }
        Insert: {
          active?: boolean
          auth_user_id: string
          created_at?: string
          email: string
          full_name: string
          id?: string
          role?: Database["public"]["Enums"]["admin_role"]
          updated_at?: string
        }
        Update: {
          active?: boolean
          auth_user_id?: string
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          role?: Database["public"]["Enums"]["admin_role"]
          updated_at?: string
        }
        Relationships: []
      }
      booking_racers: {
        Row: {
          booking_id: string
          created_at: string
          email: string | null
          friend_email_sent_at: string | null
          id: string
          name: string
          phone: string | null
          showed_up: boolean | null
          slot: number
          waiver_form_data: Json | null
          waiver_signed_at: string | null
        }
        Insert: {
          booking_id: string
          created_at?: string
          email?: string | null
          friend_email_sent_at?: string | null
          id?: string
          name: string
          phone?: string | null
          showed_up?: boolean | null
          slot: number
          waiver_form_data?: Json | null
          waiver_signed_at?: string | null
        }
        Update: {
          booking_id?: string
          created_at?: string
          email?: string | null
          friend_email_sent_at?: string | null
          id?: string
          name?: string
          phone?: string | null
          showed_up?: boolean | null
          slot?: number
          waiver_form_data?: Json | null
          waiver_signed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "booking_racers_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      bookings: {
        Row: {
          consent_fee_cents: number
          consent_ip: string | null
          consent_text: string
          consent_timestamp: string
          consent_user_agent: string | null
          created_at: string
          created_by_user_id: string | null
          customer_id: string
          duration_hours: number
          end_time: string
          google_calendar_event_id: string | null
          id: string
          no_show_fee_cents: number
          notes: string | null
          racer_count: number
          session_date: string
          session_price_cents: number
          source: Database["public"]["Enums"]["booking_source"]
          start_time: string
          status: Database["public"]["Enums"]["booking_status"]
          stripe_payment_method_id: string | null
          stripe_setup_intent_id: string | null
          updated_at: string
        }
        Insert: {
          consent_fee_cents: number
          consent_ip?: string | null
          consent_text: string
          consent_timestamp?: string
          consent_user_agent?: string | null
          created_at?: string
          created_by_user_id?: string | null
          customer_id: string
          duration_hours: number
          end_time: string
          google_calendar_event_id?: string | null
          id: string
          no_show_fee_cents: number
          notes?: string | null
          racer_count: number
          session_date: string
          session_price_cents: number
          source?: Database["public"]["Enums"]["booking_source"]
          start_time: string
          status?: Database["public"]["Enums"]["booking_status"]
          stripe_payment_method_id?: string | null
          stripe_setup_intent_id?: string | null
          updated_at?: string
        }
        Update: {
          consent_fee_cents?: number
          consent_ip?: string | null
          consent_text?: string
          consent_timestamp?: string
          consent_user_agent?: string | null
          created_at?: string
          created_by_user_id?: string | null
          customer_id?: string
          duration_hours?: number
          end_time?: string
          google_calendar_event_id?: string | null
          id?: string
          no_show_fee_cents?: number
          notes?: string | null
          racer_count?: number
          session_date?: string
          session_price_cents?: number
          source?: Database["public"]["Enums"]["booking_source"]
          start_time?: string
          status?: Database["public"]["Enums"]["booking_status"]
          stripe_payment_method_id?: string | null
          stripe_setup_intent_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      cash_drawer_entries: {
        Row: {
          amount_cents: number
          created_at: string
          created_by_user_id: string | null
          id: string
          notes: string | null
          occurred_at: string
          transaction_id: string | null
        }
        Insert: {
          amount_cents: number
          created_at?: string
          created_by_user_id?: string | null
          id?: string
          notes?: string | null
          occurred_at?: string
          transaction_id?: string | null
        }
        Update: {
          amount_cents?: number
          created_at?: string
          created_by_user_id?: string | null
          id?: string
          notes?: string | null
          occurred_at?: string
          transaction_id?: string | null
        }
        Relationships: []
      }
      customers: {
        Row: {
          birthday: string | null
          created_at: string
          email: string | null
          first_name: string
          how_heard: string | null
          id: string
          last_name: string
          last_visit_at: string | null
          marketing_opt_in: boolean
          phone: string | null
          source: string | null
          stripe_customer_id: string | null
          total_bookings: number
          total_spent_cents: number
          updated_at: string
          waiver_form_data: Json | null
          waiver_signed_at: string | null
        }
        Insert: {
          birthday?: string | null
          created_at?: string
          email?: string | null
          first_name: string
          how_heard?: string | null
          id?: string
          last_name: string
          last_visit_at?: string | null
          marketing_opt_in?: boolean
          phone?: string | null
          source?: string | null
          stripe_customer_id?: string | null
          total_bookings?: number
          total_spent_cents?: number
          updated_at?: string
          waiver_form_data?: Json | null
          waiver_signed_at?: string | null
        }
        Update: {
          birthday?: string | null
          created_at?: string
          email?: string | null
          first_name?: string
          how_heard?: string | null
          id?: string
          last_name?: string
          last_visit_at?: string | null
          marketing_opt_in?: boolean
          phone?: string | null
          source?: string | null
          stripe_customer_id?: string | null
          total_bookings?: number
          total_spent_cents?: number
          updated_at?: string
          waiver_form_data?: Json | null
          waiver_signed_at?: string | null
        }
        Relationships: []
      }
      email_log: {
        Row: {
          error: string | null
          from_email: string
          id: string
          related_booking_id: string | null
          related_customer_id: string | null
          resend_message_id: string | null
          sent_at: string
          status: string
          subject: string
          template: string
          to_email: string
        }
        Insert: {
          error?: string | null
          from_email: string
          id?: string
          related_booking_id?: string | null
          related_customer_id?: string | null
          resend_message_id?: string | null
          sent_at?: string
          status?: string
          subject: string
          template: string
          to_email: string
        }
        Update: {
          error?: string | null
          from_email?: string
          id?: string
          related_booking_id?: string | null
          related_customer_id?: string | null
          resend_message_id?: string | null
          sent_at?: string
          status?: string
          subject?: string
          template?: string
          to_email?: string
        }
        Relationships: []
      }
      expense_categories: {
        Row: {
          active: boolean
          created_at: string
          description: string | null
          id: string
          name: string
          schedule_c_line: string | null
          sort_order: number
        }
        Insert: {
          active?: boolean
          created_at?: string
          description?: string | null
          id?: string
          name: string
          schedule_c_line?: string | null
          sort_order?: number
        }
        Update: {
          active?: boolean
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          schedule_c_line?: string | null
          sort_order?: number
        }
        Relationships: []
      }
      marketing_payout_calculations: {
        Row: {
          bracket_breakdown: Json
          calculated_at: string
          computed_payout_cents: number
          gross_revenue_cents: number
          id: string
          notes: string | null
          paid: boolean
          paid_transaction_id: string | null
          period_month: number
          period_year: number
        }
        Insert: {
          bracket_breakdown: Json
          calculated_at?: string
          computed_payout_cents: number
          gross_revenue_cents: number
          id?: string
          notes?: string | null
          paid?: boolean
          paid_transaction_id?: string | null
          period_month: number
          period_year: number
        }
        Update: {
          bracket_breakdown?: Json
          calculated_at?: string
          computed_payout_cents?: number
          gross_revenue_cents?: number
          id?: string
          notes?: string | null
          paid?: boolean
          paid_transaction_id?: string | null
          period_month?: number
          period_year?: number
        }
        Relationships: []
      }
      stripe_charges: {
        Row: {
          amount_cents: number
          booking_id: string | null
          created_at: string
          currency: string
          customer_id: string | null
          decline_code: string | null
          failure_message: string | null
          id: string
          idempotency_key: string
          payment_method_type: Database["public"]["Enums"]["payment_method_type"]
          reason: string
          status: Database["public"]["Enums"]["charge_status"]
          stripe_metadata: Json | null
          stripe_payment_intent_id: string
          stripe_payment_method_id: string | null
          updated_at: string
        }
        Insert: {
          amount_cents: number
          booking_id?: string | null
          created_at?: string
          currency?: string
          customer_id?: string | null
          decline_code?: string | null
          failure_message?: string | null
          id?: string
          idempotency_key: string
          payment_method_type: Database["public"]["Enums"]["payment_method_type"]
          reason: string
          status: Database["public"]["Enums"]["charge_status"]
          stripe_metadata?: Json | null
          stripe_payment_intent_id: string
          stripe_payment_method_id?: string | null
          updated_at?: string
        }
        Update: {
          amount_cents?: number
          booking_id?: string | null
          created_at?: string
          currency?: string
          customer_id?: string | null
          decline_code?: string | null
          failure_message?: string | null
          id?: string
          idempotency_key?: string
          payment_method_type?: Database["public"]["Enums"]["payment_method_type"]
          reason?: string
          status?: Database["public"]["Enums"]["charge_status"]
          stripe_metadata?: Json | null
          stripe_payment_intent_id?: string
          stripe_payment_method_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      stripe_webhook_events: {
        Row: {
          error: string | null
          event_type: string
          id: string
          payload: Json
          processed_at: string | null
          received_at: string
          stripe_event_id: string
        }
        Insert: {
          error?: string | null
          event_type: string
          id?: string
          payload: Json
          processed_at?: string | null
          received_at?: string
          stripe_event_id: string
        }
        Update: {
          error?: string | null
          event_type?: string
          id?: string
          payload?: Json
          processed_at?: string | null
          received_at?: string
          stripe_event_id?: string
        }
        Relationships: []
      }
      transaction_audit_log: {
        Row: {
          action: string
          after_state: Json | null
          before_state: Json | null
          changed_by_user_id: string | null
          id: string
          occurred_at: string
          transaction_id: string
        }
        Insert: {
          action: string
          after_state?: Json | null
          before_state?: Json | null
          changed_by_user_id?: string | null
          id?: string
          occurred_at?: string
          transaction_id: string
        }
        Update: {
          action?: string
          after_state?: Json | null
          before_state?: Json | null
          changed_by_user_id?: string | null
          id?: string
          occurred_at?: string
          transaction_id?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          amount_cents: number
          booking_id: string | null
          created_at: string
          created_by_user_id: string | null
          customer_id: string | null
          description: string
          expense_category_id: string | null
          id: string
          occurred_on: string
          payment_method: Database["public"]["Enums"]["payment_method_type"]
          payout_period_end: string | null
          payout_period_start: string | null
          payout_recipient: string | null
          receipt_url: string | null
          soft_delete_reason: string | null
          soft_deleted_at: string | null
          soft_deleted_by_user_id: string | null
          stripe_charge_id: string | null
          tip_cents: number
          type: Database["public"]["Enums"]["transaction_type"]
          updated_at: string
          updated_by_user_id: string | null
          vendor: string | null
        }
        Insert: {
          amount_cents: number
          booking_id?: string | null
          created_at?: string
          created_by_user_id?: string | null
          customer_id?: string | null
          description: string
          expense_category_id?: string | null
          id?: string
          occurred_on: string
          payment_method: Database["public"]["Enums"]["payment_method_type"]
          payout_period_end?: string | null
          payout_period_start?: string | null
          payout_recipient?: string | null
          receipt_url?: string | null
          soft_delete_reason?: string | null
          soft_deleted_at?: string | null
          soft_deleted_by_user_id?: string | null
          stripe_charge_id?: string | null
          tip_cents?: number
          type: Database["public"]["Enums"]["transaction_type"]
          updated_at?: string
          updated_by_user_id?: string | null
          vendor?: string | null
        }
        Update: {
          amount_cents?: number
          booking_id?: string | null
          created_at?: string
          created_by_user_id?: string | null
          customer_id?: string | null
          description?: string
          expense_category_id?: string | null
          id?: string
          occurred_on?: string
          payment_method?: Database["public"]["Enums"]["payment_method_type"]
          payout_period_end?: string | null
          payout_period_start?: string | null
          payout_recipient?: string | null
          receipt_url?: string | null
          soft_delete_reason?: string | null
          soft_deleted_at?: string | null
          soft_deleted_by_user_id?: string | null
          stripe_charge_id?: string | null
          tip_cents?: number
          type?: Database["public"]["Enums"]["transaction_type"]
          updated_at?: string
          updated_by_user_id?: string | null
          vendor?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      admin_role: "owner" | "staff" | "sweet_dreams" | "readonly"
      booking_source: "online" | "admin" | "imported"
      booking_status:
        | "pending"
        | "confirmed"
        | "completed"
        | "partial_noshow"
        | "noshow"
        | "cancelled"
      charge_status:
        | "pending"
        | "succeeded"
        | "failed"
        | "requires_action"
        | "refunded"
      payment_method_type:
        | "stripe_online"
        | "stripe_terminal"
        | "cash"
        | "other"
        | "internal"
      transaction_type:
        | "booking_income"
        | "no_show_fee"
        | "in_person_sale"
        | "other_income"
        | "expense"
        | "owner_payout"
        | "employee_payout"
        | "marketing_payout"
        | "cash_deposit"
        | "cash_withdrawal"
        | "refund"
        | "adjustment"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
